name: nihaonas

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "bromolow-7.0.1-42218"
    strategy:
      fail-fast: false
      matrix:
       include:
         - platform: bromolow
           version: 7.0.1-42218
    steps:
      - name: 准备结束
        uses: actions/checkout@v2

      - name: 缓存加速
        uses: actions/cache@v2
        with:
          path: |
            cache/*.pat
            docker/downloads/*.txz
          key: bromolow-7.0.1-42218-global_config.json

      - name: 准备构建环境
        run: |
          ./redpill_tool_chain.sh build bromolow-7.0.1-42218

      - name: 配置引导镜像
        run: |
          cp sample_user_config.json bromolow_user_config.json
          sed -i -e 's\0x0001\0x0002\g' -e 's\0x46f4\0x0002\g' -e 's\1234XXX123\0123456789\g' -e 's\XXYYXXYYXXYY\00AAAAAAAAAA\g' -e 's/00AAAAAAAAAA"/&,\n\t"mac2": "00BBBBBBBBBB",\n\t"netif_num": 2/' -e 's/"synoinfo": {},/"synoinfo": {\n\t"maxlanport": "2"\n    },/' bromolow_user_config.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/alx/rpext-index.json

      - name: 编译引导镜像
        run: ./redpill_tool_chain.sh auto bromolow-7.0.1-42218


      - uses: actions/upload-artifact@v2
        with:
          name: ds3615
          path: ./images
